package com.jc.ems.constant;

public class MessageConstant {
	
	public static final String defaultTitle = "Information Message";
	public static final String defaultError = "Error Message";
	public static final String defaultHeader = "Message Displayed !!!!!!";
	public static final String invalidLogin = "Username and Password is either disabled or doesn't exists!!!";
	public static final String validLogin = "Login successful by ";
	public static final String welcomeBack = "Logged in User: ";
	public static final String existsEmployeeId = "The Employee Id specified already exists!";
	public static final String defaultLength30 = "Allowed length is 30 char for field: ";
	public static final String employeeIdMandatory = "Employee Id is Mandatory!";
	public static final String notEmployeeId = "Employee Id doesn't exists!";
	public static final String addEmployeeSuccess = "Employee information added successfully.";
	public static final String allowedLeaves = "You have exceed you current month allowed leaves quote!";
	public static final String leaveMandtory = "Leave Date is mandatory to add leave!";
	public static final String wagesBy = "Salary generated by ";
	public static final String updateMessageSuccess = "Update completed sucessfully";
	public static final String updateMessageFailure = "Update failed, Please check the input!";
}
